/* 
[FOOD_FACTORY] 식품공장의 정보 테이블

FACTORY_ID 공장 ID
FACTORY_NAME 공장 이름
ADDRESS 주소
TLNO 전화번호
 */

select FACTORY_ID, FACTORY_NAME, ADDRESS
from FOOD_FACTORY
WHERE ADDRESS like '강원도%'
ORDER BY FACTORY_ID ASC;