/* 
[ANIMAL_INS] 동물 보호소에 들어온 동물의 정보 테이블

ANIMAL_ID 동물의 아이디
ANIMAL_TYPE 생물 종
DATETIME 보호 시작일
INTAKE_CONDITION 보호 시작 시 상태
NAME 이름
SEX_UPON_INTAKE 성별 및 중성화 여부
 */

SELECT ANILMA_ID, NAME
from ANIMAL_INS
WHERE INTAKE_CONDITION = "Aged"
ORDER BY ANIMAL_ID ASC;